{% set name = "smqtk-dataprovider" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smqtk_dataprovider-{{ version }}.tar.gz
  sha256: 5b509990501666755ae95d75e84d7f8fd41d92f8052431a84a7ffde78489b59d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.23.5,<2.0  # [py<=312]
    - numpy >=2.1  # [py>312]
    - requests >=2.28.1
    - smqtk-core >=0.20
    - psycopg2-binary >=2.9.10

test:
  imports:
    - smqtk_dataprovider
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kitware/SMQTK-Dataprovider
  summary: SMQTK Data provision abstractions and implementations
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - barry-ravichandran
